# Simple makefile, just for convenience.

PYTHON = python
PYTEST = pytest
SPHINXBUILD = sphinx-build
SPHINXOPTS =
PYTEST_OPTS = -n auto

install:
	$(PYTHON) -m pip install . --no-deps --ignore-installed --no-cache-dir --no-index --no-build-isolation -vvv

# install to "develop" mode. This sets up a link to the source code, so we
# can modify the source and immediately see the results in using pynitf
install-develop:
	$(PYTHON) -m pip install -e . --no-deps --ignore-installed --no-cache-dir --no-index --no-build-isolation -vvv

# variation that installs the source into $AFIDSPYTHONTOP, since this
# is something we commonly do during development. Note you may also want
# to install usercustomize.py, see this is the extra directory. Without this,
# the .pth file generated by this install may not get processed.
install-develop-afids:
	echo "May also want to run install-usercustomize-afids"
	$(PYTHON) -m pip install -e . --no-deps --ignore-installed --no-cache-dir --no-index --prefix $(AFIDSPYTHONTOP) -vvv

install-usercustomize-afids:
	cp extra/usercustomize.py $(AFIDSPYTHONTOP)/lib/python*/site-packages

check:
	export PYTHONPATH=$(shell pwd) && $(PYTEST) $(PYTEST_OPTS) -rxXs tests

# Put it first so that "make" without argument is like "make help".
doc-help:
	@export PYTHONPATH=$(shell pwd) && $(SPHINXBUILD) -M help doc doc/_build $(SPHINXOPTS)

doc-html: 
	@export PYTHONPATH=$(shell pwd) && $(SPHINXBUILD) -M html doc doc/_build $(SPHINXOPTS)

doc-latex: 
	@export PYTHONPATH=$(shell pwd) && $(SPHINXBUILD) -M latex doc doc/_build $(SPHINXOPTS)

doc-latexpdf: 
	@export PYTHONPATH=$(shell pwd) && $(SPHINXBUILD) -M latexpdf doc doc/_build $(SPHINXOPTS)

#=================================================================
# Upload documentation to github pages
# *Note* I tend to forget this, but there needs to be a .nojekyll in
# the github pages for github to serve the page right. This can be done
# by just adding .nojekyll to doc/_build/html. This has already been done
# for this repository. Newer versions of ghp-import also have a "-n" option
# to add the .nojekyll file
github-pages: doc-html
	@echo "Note, this should usually be done from the main branch only"
	ghp-import -n doc/_build/html -m "Update pynitf documentation"
	@echo "You now need to push the gh-pages branch to github for these to be visible (git push origin gh-pages)"

# ------------------------------------------------------------------
# It is *not* considered an error to fail these, however the output of
# the linter and type checker can useful. We try to get all the errors
# fixed just to reduce the noise in the output. You can also often
# just silence errors for things that aren't worth fixing. We aren't
# required to make the linter or type checker happy - just to write
# python code that works. But it is mildly useful to have everything
# cleanly passing so we can see the occasional real thing that the
# linter or type checker finds.
#
# Also it isn't a requirement to match the format that ruff or other
# formater want. But it is pretty easy just to run the tools to get
# constistent code, so we tend to do that.
# ------------------------------------------------------------------

lint:
	ruff check pynitf tests

# Add some extra rules
lint-strict:
	ruff check --extend-select N pynitf tests

lint-fix:
	ruff check --fix pynitf tests

format:
	ruff format pynitf tests

# ------------------------------------------------------------------
# Note, typing isn't in place for pynitf. We may get to that at
# some point, but for now just set up rules to be able to run this.
# ------------------------------------------------------------------

# Note that PYTHONPATH is required, at least as of pip 24.3.1. The py.typed file needed to
# tell mypy that our modules have types doesn't get translated through using
# editable mode of pip. This is an issue going back at least a few years that hasn't
# been addressed - see https://github.com/python/mypy/issues/13392. We work around this
# just by giving a explicit path to our source code skipping going through the installed
# version. This is only for type checking, all our other tests/check use the pip installed
# version.
mypy-simplier:
	PYTHONPATH=$(PWD) mypy pynitf

# This adds options to check for missing typing info. We usually want this
mypy:
	PYTHONPATH=$(PWD) mypy --disallow-untyped-defs pynitf


# ------------------------------------------------------------------
# Create a development environment using pixi. Note there is no
# requirement that conda/pixi be used, it can just be nice to easily
# create a stand alone development environment when working on
# pynitf
# ------------------------------------------------------------------

dev-env:
	-rm -r .pixi pixi.lock pixi.toml
	pixi init .
	pixi add numpy docopt-ng h5py jsonpickle pytest pytest-xdist ruff mypy Sphinx ghp-import sphinxcontrib-plantuml ptpython python pip setuptools ipython pyxb lxml xmlschema jsonpickle
	pixi run python -m pip install -e . --no-deps --ignore-installed --no-cache-dir --no-index --no-build-isolation -vvv
	echo "Execute 'pixi shell' to use development environment."
