# Newer versions of pip prefer a pyproject.toml file. All this does is say
# we are using setup tools. Note that this also triggers "build isolation"
# We don't actually need or want this, instead we want to use the packages we
# have already installed with conda. So we use --no-build-isolation when
# we install this with pip:
#
# pip install . --no-build-isolation

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff.lint.per-file-ignores]

# __init__ includes things it doesn't use (e.g., __version__), which
# is really its job. So don't warn about this.

"__init__.py" = ["F401", "F403"]

# Have some unused variables in nitf_diff_handle, but they are escape sequences
# we aren't using the log output but might in the future
"nitf_diff_handle.py" = ["F841",]

[tool.pixi.workspace]
name = "pynitf"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
pynitf = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
numpy = "*"
docopt-ng = "*"
h5py = "*"
jsonpickle = "*"
pytest = "*"
pytest-xdist = "*"
ruff = "*"
mypy = "*"
sphinx = "*"
ghp-import = "*"
sphinxcontrib-plantuml = "*"
ptpython = "*"
python = "*"
pip = "*"
setuptools = "*"
