#! /usr/bin/env python
from __future__ import print_function
import pynitf
import subprocess
import os
import sys

version="%prog June 6, 2019"
usage="""Usage: 
  nitfinfofull [options] <input_file>
  nitfinfofull -h | --help
  nitfinfofull -v | --version

Print out full information about a NITF file.

This program is equivalent to running nitfinfo --full in geocal

Options:
  -h --help         
       Print this message

  --debug
       Turn on debugging statements in pynitf

  -v --version      
       Print program version

"""
args = pynitf.docopt_simple.docopt_simple(usage, version=version)

if(args.debug):
    pynitf.nitf_field.DEBUG = True
    pynitf.nitf_des.DEBUG = True
f = pynitf.NitfFile(args.input_file)
print(f)
